
import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'apple-mac-mini-m4-chip',
    name: 'Apple Mac Mini M4 Chip',
    description: 'Compact desktop powered by M4 chip and Neural Engine, with Thunderbolt 4 ports.',
    price: 1399,
    images: ['https://cdn.shopify.com/s/files/1/0869/3327/4960/files/mac-mini-202410-gallery-1-461061.webp?v=1736116568'],
    specs: {
      storage: '512GB SSD',
      color: 'Silver',
      display: 'N/A',
    },
    features: ['M4 Chip', 'Neural Engine', 'Thunderbolt 4', 'Compact design'],
    stock: 25,
  },
  {
    id: 'macbook-pro-m4-chip-14-inch-24gb-1tb',
    name: 'MacBook Pro M4 Chip 14-inch (24GB/1TB)',
    description: 'Powerful 14-inch MacBook Pro with M4 chip, 24GB RAM and 1TB SSD, ideal for professionals.',
    price: 2499,
    images: ['https://cdn.shopify.com/s/files/1/0869/3327/4960/files/MACBOOKM41_2bcf82be-f5c2-47d1-9200-7858dcf39ea7.jpg?v=1736116591'],
    specs: {
      storage: '1TB SSD',
      color: 'Space Black',
      display: '14-inch Liquid Retina XDR',
    },
    features: ['M4 Chip', '24GB Unified Memory', '1TB SSD', 'Liquid Retina XDR Display'],
    stock: 15,
  },
  {
    id: 'airpods-4-new',
    name: 'AirPods 4 New',
    description: 'Latest generation of AirPods with improved sound and battery life.',
    price: 279,
    images: ['https://cdn.shopify.com/s/files/1/0869/3327/4960/files/AIRPODS41.jpg?v=1736116638'],
    specs: {
      storage: 'N/A',
      color: 'White',
      display: 'N/A',
    },
    features: ['Active Noise Cancellation', 'Spatial Audio', 'All-day battery life', 'Sweat and water resistant'],
    stock: 150,
  },
  {
    id: 'apple-watch-series-10',
    name: 'Apple Watch Series 10',
    description: 'Sleek design and enhanced health tracking in the 10th-gen Apple Watch.',
    price: 499,
    images: ['https://cdn.shopify.com/s/files/1/0869/3327/4960/files/WhatsApp_Image_2024-09-13_at_11.32.29_PM_2_4d44a034-3912-4297-ac16-05342290afe1-129837.png?v=1736116654'],
    specs: {
      storage: '64GB',
      color: 'Midnight Aluminum',
      display: 'Always-On Retina display',
    },
    features: ['New Health Sensor', 'Crash Detection', 'Temperature Sensing', 'Enhanced Durability'],
    stock: 80,
  },
  {
    id: 'samsung-z-flip-6',
    name: 'Samsung Z Flip 6',
    description: 'Foldable smartphone with premium features and modern design.',
    price: 1099,
    images: ['https://cdn.shopify.com/s/files/1/0869/3327/4960/files/NewProject_9.webp?v=1739206482'],
    specs: {
      storage: '256GB',
      color: 'Bora Purple',
      display: '6.7-inch Foldable Dynamic AMOLED',
    },
    features: ['Flex Mode', 'Compact Foldable Design', 'Nightography Camera', 'Enhanced Cover Screen'],
    stock: 45,
  },
  {
    id: 'iphone-16-pro-max-tdra-dubai-version',
    name: 'iPhone 16 Pro Max TDRA (Dubai Version)',
    description: 'Latest iPhone with enhanced camera, performance, and Dubai-compliant version.',
    price: 1299,
    images: ['https://cdn.shopify.com/s/files/1/0869/3327/4960/files/16PROMAX_85347601-4b58-4e23-83a1-dddf568487bf.jpg?v=1736116681'],
    specs: {
      storage: '256GB',
      color: 'Desert Titanium',
      display: '6.9-inch Super Retina XDR',
    },
    features: ['A18 Bionic Chip', 'Tetraprism Telephoto lens', 'Action button', 'TDRA Certified'],
    stock: 30,
  },
  {
    id: 'iphone-17',
    name: 'iPhone 17',
    description: 'Future-ready iPhone model with new features and design.',
    price: 1399,
    images: ['https://cdn.shopify.com/s/files/1/0869/3327/4960/files/WhatsApp_Image_2024-09-13_at_11.28.24_PM.jpg?v=1736116712'],
    specs: {
      storage: '256GB',
      color: 'Cosmic Blue',
      display: '6.3-inch Super Retina XDR',
    },
    features: ['A19 Chip', 'Under-display Camera', 'Haptic Buttons', 'Periscope Lens'],
    stock: 39,
  },
  {
    id: 'iphone-xs-max',
    name: 'iPhone XS Max',
    description: '6.5" display, dual camera, and Face ID in a classic premium iPhone.',
    price: 549,
    images: ['https://cdn.shopify.com/s/files/1/0869/3327/4960/files/xsmax.jpg?v=1736116724'],
    specs: {
      storage: '256GB',
      color: 'Gold',
      display: '6.5-inch Super Retina HD display',
    },
    features: ['A12 Bionic chip', 'Dual 12MP cameras', 'Face ID', 'Splash, Water, and Dust Resistant'],
    stock: 65,
  },
  {
    id: 'iphone-x',
    name: 'iPhone X',
    description: 'Edge-to-edge OLED display, Face ID, and compact power.',
    price: 499,
    images: ['https://cdn.shopify.com/s/files/1/0869/3327/4960/files/x.jpg?v=1736116729'],
    specs: {
      storage: '64GB',
      color: 'Space Gray',
      display: '5.8-inch Super Retina HD display',
    },
    features: ['A11 Bionic chip', 'Face ID', 'TrueDepth Camera', 'Wireless Charging'],
    stock: 88,
  },
  {
    id: 'data-cable',
    name: 'Data Cable',
    description: 'Fast-charging and sync USB cable, compatible with various devices.',
    price: 25,
    images: ['https://cdn.shopify.com/s/files/1/0869/3327/4960/files/charging_cable.webp?v=1740743755'],
    specs: {
      storage: 'N/A',
      color: 'White',
      display: 'N/A',
    },
    features: ['USB-C to Lightning', 'Fast Charging', 'Braided Cable', '1 Meter Length'],
    stock: 200,
  },
  {
    id: 'macbook-pro-m3',
    name: 'MacBook Pro M3',
    description: 'M3-powered MacBook for advanced performance and long battery life.',
    price: 1999,
    images: ['https://static.independent.co.uk/2023/11/06/13/Macbook-1.png'],
    specs: {
      storage: '512GB SSD',
      color: 'Silver',
      display: '14-inch Liquid Retina XDR',
    },
    features: ['M3 Chip', '16GB Unified Memory', '512GB SSD', 'Liquid Retina XDR Display'],
    stock: 20,
  },
  {
    id: 'ipad-pro-12-9-inch',
    name: 'iPad Pro 12.9"',
    description: 'Large display iPad with Apple Pencil support for creatives and professionals.',
    price: 1099,
    images: ['https://www.classic-phones.com/cdn/shop/products/03-anker-branding-1024x576_9ce10f2e-f05d-403a-bd69-b89bc172bf14.jpg?v=1673527469'],
    specs: {
      storage: '256GB',
      color: 'Space Gray',
      display: '12.9-inch Liquid Retina XDR',
    },
    features: ['M2 Chip', 'ProMotion technology', 'Face ID', 'Thunderbolt / USB 4'],
    stock: 35,
  },
  {
    id: 'apple-pencil-3rd-gen',
    name: 'Apple Pencil 3rd Gen',
    description: 'Precision stylus for iPad, great for drawing, notes, and editing.',
    price: 129,
    images: ['https://image.made-in-china.com/202f0j00qabepVjIhDkl/Factory-Price-for-Stylus-Pens-for-Apple-for-iPad-Pen-Touch-Screen-Pen-for-Apple-Pencil-2ND-Generation-for-Magnetic-Pencil.webp'],
    specs: {
      storage: 'N/A',
      color: 'White',
      display: 'N/A',
    },
    features: ['Pixel-perfect precision', 'Low latency', 'Tilt and pressure sensitivity', 'Magnetic attachment'],
    stock: 120,
  },
  {
    id: 'samsung-galaxy-s25-ultra',
    name: 'Samsung Galaxy S25 Ultra',
    description: 'Flagship Samsung phone with top-tier specs and camera.',
    price: 1199,
    images: ['https://images.olx.com.pk/thumbnails/554061345-240x180.jpeg'],
    specs: {
      storage: '512GB',
      color: 'Phantom Black',
      display: '6.8-inch Dynamic AMOLED 2X',
    },
    features: ['200MP Camera', 'S Pen Included', 'Gorilla Glass Victus 3', '5000mAh Battery'],
    stock: 40,
  },
  {
    id: 'iphone-13-mini',
    name: 'iPhone 13 Mini',
    description: 'Compact iPhone with powerful internals and vibrant display.',
    price: 699,
    images: ['https://cdn.homeshopping.pk/product_images/i/121/61KeIxmldLL._SL1500___86370_zoom.jpg'],
    specs: {
      storage: '128GB',
      color: 'Starlight',
      display: '5.4-inch Super Retina XDR',
    },
    features: ['A15 Bionic chip', 'Dual-camera system', 'Ceramic Shield', '5G capable'],
    stock: 55,
  },
  {
    id: 'apple-tv-4k',
    name: 'Apple TV 4K',
    description: 'Smart streaming box with 4K HDR support and Siri Remote.',
    price: 179,
    images: ['https://myshop.pk/pub/media/catalog/product/cache/26f8091d81cea4b38d820a1d1a4f62be/a/p/apple_tv_4k_2nd_gen_-_32gb_myshop-pk-2.jpg'],
    specs: {
      storage: '64GB',
      color: 'Black',
      display: 'N/A',
    },
    features: ['4K High Frame Rate HDR', 'Dolby Atmos', 'A15 Bionic chip', 'Siri Remote'],
    stock: 90,
  },
  {
    id: 'airtag-4-pack',
    name: 'AirTag (4 Pack)',
    description: 'Bluetooth tracker to locate keys, bags, or personal items.',
    price: 99,
    images: ['https://5.imimg.com/data5/SELLER/Default/2023/3/SU/YD/OI/184984620/img-7613-500x500.jpg'],
    specs: {
      storage: 'N/A',
      color: 'White',
      display: 'N/A',
    },
    features: ['Precision Finding', 'One-tap setup', 'Find My network', 'Water resistant'],
    stock: 300,
  },
  {
    id: 'apple-magic-mouse',
    name: 'Apple Magic Mouse',
    description: 'Wireless rechargeable mouse with sleek multi-touch surface.',
    price: 79,
    images: ['https://talk.tidbits.com/uploads/default/original/2X/0/074e125a63b364af957e1680b763d7f3ffdf2b94.jpeg'],
    specs: {
      storage: 'N/A',
      color: 'White',
      display: 'N/A',
    },
    features: ['Rechargeable', 'Multi-Touch surface', 'Wireless Bluetooth', 'Optimized foot design'],
    stock: 85,
  },
  {
    id: 'mac-studio',
    name: 'Mac Studio',
    description: 'High-performance desktop for creators and developers.',
    price: 1999,
    images: ['https://cdn.shopify.com/s/files/1/0869/3327/4960/files/macstudio.jpg?v=1736116999'],
    specs: {
      storage: '1TB SSD',
      color: 'Silver',
      display: 'N/A',
    },
    features: ['M2 Max or M2 Ultra chip', 'Extensive connectivity', 'Compact design', 'Runs macOS'],
    stock: 18,
  },
  {
    id: 'apple-keyboard',
    name: 'Apple Keyboard',
    description: 'Low-profile, Bluetooth-enabled magic keyboard.',
    price: 99,
    images: ['https://i.roamcdn.net/hz/pi/listing-thumb-543w/26cd47a6d2522bc8fe665d3505e4671d/-/horizon-files-prod/pi/picture/q0gknkjd/032c92a16aa0d077f393f33ae38ccd57a3f84e5a.jpg'],
    specs: {
      storage: 'N/A',
      color: 'Silver',
      display: 'N/A',
    },
    features: ['Rechargeable battery', 'Wireless', 'Stable scissor mechanism', 'Comfortable typing'],
    stock: 110,
  },
  {
    id: 'beats-studio-pro',
    name: 'Beats Studio Pro',
    description: 'Over-ear wireless headphones with noise cancelation.',
    price: 349,
    images: ['https://openbox.ca/cdn/shop/files/0_ac3dea8a-8095-4007-9e06-0aab24988f64_1200x.jpg?v=1750182606'],
    specs: {
      storage: 'N/A',
      color: 'Black',
      display: 'N/A',
    },
    features: ['Active Noise Cancelling', 'Spatial Audio', 'Up to 40 hours of battery life', 'On-device controls'],
    stock: 60,
  },
  {
    id: 'apple-watch-se-2nd-gen',
    name: 'Apple Watch SE 2nd Gen',
    description: 'Affordable Apple Watch with essential features.',
    price: 249,
    images: ['https://i0.wp.com/macdailynews.com/wp-content/uploads/2023/09/230912_apple_watch_se.png'],
    specs: {
      storage: '32GB',
      color: 'Silver',
      display: 'Retina LTPO OLED display',
    },
    features: ['Crash Detection', 'Family Setup', 'Water resistant', 'Heart rate notifications'],
    stock: 75,
  },
  {
    id: 'apple-watch-ultra',
    name: 'Apple Watch Ultra',
    description: 'Rugged smartwatch built for adventure and endurance.',
    price: 799,
    images: ['https://images.priceoye.pk/apple-watch-ultra-49mm-pakistan-priceoye-uovmj-500x500.webp'],
    specs: {
      storage: '64GB',
      color: 'Titanium',
      display: 'Always-On Retina display',
    },
    features: ['Titanium case', 'Precision dual-frequency GPS', 'Water resistance 100m', 'Customizable Action button'],
    stock: 30,
  },
  {
    id: 'iphone-12-pro',
    name: 'iPhone 12 Pro',
    description: 'Triple-camera system with LiDAR and ProRAW features.',
    price: 899,
    images: ['https://images.priceoye.pk/apple-iphone-12-pro-pakistan-priceoye-2mmvz.jpg'],
    specs: {
      storage: '256GB',
      color: 'Pacific Blue',
      display: '6.1-inch Super Retina XDR',
    },
    features: ['A14 Bionic chip', 'Pro camera system', 'Ceramic Shield', 'LiDAR Scanner'],
    stock: 48,
  },
  {
    id: 'macbook-air-m2',
    name: 'MacBook Air M2',
    description: 'Slim and light notebook with all-day battery and performance.',
    price: 1199,
    images: ['https://ivenus.in/wp-content/uploads/2025/01/0-768x768.jpeg'],
    specs: {
      storage: '512GB SSD',
      color: 'Midnight',
      display: '13.6-inch Liquid Retina display',
    },
    features: ['M2 chip', '1080p FaceTime HD camera', 'MagSafe 3 charging', 'Fanless design'],
    stock: 42,
  },
  {
    id: 'iphone-15-plus',
    name: 'iPhone 15 Plus',
    description: 'Big display iPhone with long battery and enhanced camera.',
    price: 899,
    images: ['https://images.priceoye.pk/media/apple-iphone-15-plus/apple-iphone-15-plus-jf1nw.jpg'],
    specs: {
      storage: '256GB',
      color: 'Blue',
      display: '6.7-inch Super Retina XDR',
    },
    features: ['Dynamic Island', 'A16 Bionic chip', '48MP Main camera', 'USB-C connector'],
    stock: 68,
  },
  {
    id: 'imac-m3-24-inch',
    name: 'iMac M3 24-inch',
    description: 'All-in-one desktop with vibrant display and M3 chip.',
    price: 1299,
    images: ['https://www.apple.com/newsroom/images/2023/10/apple-supercharges-24-inch-imac-with-new-m3-chip/article/Apple-iMac-M3-color-matched-accessories-231030_big.jpg.large.jpg'],
    specs: {
      storage: '256GB SSD',
      color: 'Green',
      display: '24-inch 4.5K Retina display',
    },
    features: ['M3 chip', '1080p FaceTime HD camera', 'Six-speaker sound system', 'Color-matched accessories'],
    stock: 28,
  },
  {
    id: 'ipad-mini-6',
    name: 'iPad Mini 6',
    description: 'Small, powerful iPad for reading and portability.',
    price: 499,
    images: ['https://static-01.daraz.pk/p/7730924ac95814a5621ee77d12b538c5.jpg'],
    specs: {
      storage: '64GB',
      color: 'Purple',
      display: '8.3-inch Liquid Retina display',
    },
    features: ['A15 Bionic chip', 'USB-C port', '12MP Ultra Wide front camera', 'Apple Pencil (2nd gen) support'],
    stock: 70,
  },
  {
    id: 'apple-watch-series-9',
    name: 'Apple Watch Series 9',
    description: 'Updated sensors, better screen, and fast charging.',
    price: 399,
    images: ['https://games4u.pk/cdn/shop/files/F70.jpg'],
    specs: {
      storage: '64GB',
      color: 'Pink',
      display: 'Always-On Retina display',
    },
    features: ['S9 SiP', 'Double tap gesture', 'Brighter display', 'Temperature sensing'],
    stock: 95,
  },
  {
    id: 'airpods-pro-2',
    name: 'AirPods Pro 2',
    description: 'Noise-canceling earbuds with spatial audio and improved fit.',
    price: 249,
    images: ['https://technoshop.pk/wp-content/uploads/2024/02/Apple-AirPods-Pro-2-Copy-White.jpg'],
    specs: {
      storage: 'N/A',
      color: 'White',
      display: 'N/A',
    },
    features: ['Up to 2x more Active Noise Cancellation', 'Adaptive Transparency', 'Personalized Spatial Audio', 'Touch control'],
    stock: 180,
  },
  {
    id: 'iphone-se-3rd-gen',
    name: 'iPhone SE 3rd Gen',
    description: 'Budget iPhone with A15 chip and Touch ID.',
    price: 429,
    images: ['https://www.getorchard.com/cdn/shop/products/iphone-se-2022.png'],
    specs: {
      storage: '128GB',
      color: 'Red',
      display: '4.7-inch Retina HD display',
    },
    features: ['A15 Bionic chip', '5G connectivity', 'Durable design', 'Touch ID'],
    stock: 130,
  },
  {
    id: 'ipad-air-5',
    name: 'iPad Air 5',
    description: 'Thin and powerful mid-range tablet with M1 chip.',
    price: 599,
    images: ['https://images.priceoye.pk/apple-ipad-air-5-pakistan-priceoye-zw5ue.jpg'],
    specs: {
      storage: '256GB',
      color: 'Blue',
      display: '10.9-inch Liquid Retina display',
    },
    features: ['M1 chip', '12MP Ultra Wide front camera', 'Center Stage', 'Works with Apple Pencil (2nd gen)'],
    stock: 65,
  },
  {
    id: 'apple-airpods-max',
    name: 'Apple AirPods Max',
    description: 'High-end over-ear headphones with spatial audio.',
    price: 549,
    images: ['https://shopivate.pk/wp-content/uploads/2023/05/1000135015.jpg'],
    specs: {
      storage: 'N/A',
      color: 'Sky Blue',
      display: 'N/A',
    },
    features: ['High-fidelity audio', 'Active Noise Cancellation', 'Spatial audio', 'Knit-mesh canopy'],
    stock: 45,
  },
  {
    id: 'apple-20w-usb-c-adapter',
    name: 'Apple 20W USB-C Adapter',
    description: 'Fast charging wall adapter for iPhone and iPad.',
    price: 19,
    images: ['https://static-01.daraz.pk/p/fc4bf6b07ad91f472a4712cd4db6f28d.jpg'],
    specs: {
      storage: 'N/A',
      color: 'White',
      display: 'N/A',
    },
    features: ['20W output', 'Fast charging', 'USB-C', 'Compact design'],
    stock: 250,
  },
  {
    id: 'apple-watch-band-sport-loop',
    name: 'Apple Watch Band Sport Loop',
    description: 'Breathable and lightweight Apple Watch strap.',
    price: 49,
    images: ['https://mac-more.co.ke/wp-content/uploads/2024/02/Apple_Watch_SE_GPS_44mm_Silver_Aluminum_Winter_Blue_Sport_Loop_PDP_Image_2023_Position-1__WWEN.jpg'],
    specs: {
      storage: 'N/A',
      color: 'Storm Blue',
      display: 'N/A',
    },
    features: ['Soft and breathable', 'Hook-and-loop fastener', 'Durable', 'Lightweight'],
    stock: 150,
  },
  {
    id: 'magic-trackpad',
    name: 'Magic Trackpad',
    description: 'Touch-sensitive surface for gestures and productivity.',
    price: 129,
    images: ['https://i.ebayimg.com/images/g/t~gAAOSwd7Bho-1k/s-l1200.jpg'],
    specs: {
      storage: 'N/A',
      color: 'White',
      display: 'N/A',
    },
    features: ['Force Touch', 'Multi-Touch gestures', 'Wireless and rechargeable', 'Large edge-to-edge glass surface'],
    stock: 60,
  },
  {
    id: 'apple-studio-display',
    name: 'Apple Studio Display',
    description: '5K Retina monitor with Thunderbolt support.',
    price: 1599,
    images: ['https://m.media-amazon.com/images/I/71Xc+x-QyiL.jpg'],
    specs: {
      storage: 'N/A',
      color: 'Silver',
      display: '27-inch 5K Retina display',
    },
    features: ['12MP Ultra Wide camera with Center Stage', 'Studio-quality mics', 'Six-speaker sound system', 'Thunderbolt 3 port'],
    stock: 22,
  },
  {
    id: 'iphone-14',
    name: 'iPhone 14',
    description: 'Dual-camera iPhone with A15 chip and crash detection.',
    price: 799,
    images: ['https://applehub.pk/wp-content/uploads/2022/09/iphone-14-starlight-1.jpg'],
    specs: {
      storage: '128GB',
      color: 'Midnight',
      display: '6.1-inch Super Retina XDR',
    },
    features: ['A15 Bionic chip', 'Advanced dual-camera system', 'Emergency SOS via satellite', 'All-day battery life'],
    stock: 80,
  },
  {
    id: 'apple-watch-charger-magnetic',
    name: 'Apple Watch Charger Magnetic',
    description: 'Official magnetic charging cable for Apple Watch.',
    price: 29,
    images: ['https://www.tjmart.pk/image/cache/catalog/products/Apple-Watch-USB-Magnetic-Charging-Cable-Copy/item_4319548_181-800x800.jpg'],
    specs: {
      storage: 'N/A',
      color: 'White',
      display: 'N/A',
    },
    features: ['Magnetic charging', '1m cable length', 'USB-C connector', 'Fast charging for select models'],
    stock: 190,
  },
  {
    id: 'apple-silicone-case',
    name: 'Apple Silicone Case',
    description: 'Smooth silicone case designed to fit iPhone models perfectly.',
    price: 49,
    images: ['https://casedrip.pk/cdn/shop/files/4320CE39-787D-48FC-9E56-95F80E82D309.jpg?v=1741968223'],
    specs: {
      storage: 'N/A',
      color: 'Chalk Pink',
      display: 'N/A',
    },
    features: ['Soft-touch finish', 'Microfiber lining', 'MagSafe compatible', 'Protects from scratches and drops'],
    stock: 220,
  }
];
