
import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'apple-mac-mini-m4-chip-neural-engine-thunderbolt-4-ports',
    name: 'Apple Mac Mini M4 Chip Neural Engine Thunderbolt 4 Ports',
    description: 'Experience the next level of performance with the M4 chip. Compact design, powerful graphics, and advanced neural engine capabilities.',
    price: 1399,
    images: ['https://cdn.shopify.com/s/files/1/0869/3327/4960/files/mac-mini-202410-gallery-1-461061.webp?v=1736116568'],
    specs: {
      storage: '512GB SSD',
      color: 'Silver',
      display: 'N/A',
    },
    features: ['M4 Chip', 'Neural Engine', 'Thunderbolt 4', 'Compact design'],
    stock: 25,
  },
  {
    id: 'macbook-pro-m4-chip-14-inch-24gb-1tb',
    name: 'Macbook Pro M4 Chip 14 Inch 24gb 1tb',
    description: 'The ultimate pro laptop, supercharged by the M4 chip for groundbreaking performance and a stunning Liquid Retina XDR display.',
    price: 2499,
    images: ['https://cdn.shopify.com/s/files/1/0869/3327/4960/files/MACBOOKM41_2bcf82be-f5c2-47d1-9200-7858dcf39ea7.jpg?v=1736116591'],
    specs: {
      storage: '1TB SSD',
      color: 'Space Black',
      display: '14-inch Liquid Retina XDR',
    },
    features: ['M4 Chip', '24GB Unified Memory', '1TB SSD', 'Liquid Retina XDR Display'],
    stock: 15,
  },
  {
    id: 'air-pods-4-new',
    name: 'Air Pods 4 New',
    description: 'Introducing the new AirPods 4 with immersive sound, longer battery life, and a sleek new design. Magic, remastered.',
    price: 279,
    images: ['https://cdn.shopify.com/s/files/1/0869/3327/4960/files/AIRPODS41.jpg?v=1736116638'],
    specs: {
      storage: 'N/A',
      color: 'White',
      display: 'N/A',
    },
    features: ['Active Noise Cancellation', 'Spatial Audio', 'All-day battery life', 'Sweat and water resistant'],
    stock: 150,
  },
  {
    id: 'apple-10-series-watch',
    name: 'Apple 10 Series Watch',
    description: 'The most advanced Apple Watch yet, with a revolutionary new health sensor and a brighter, more durable display.',
    price: 499,
    images: ['https://cdn.shopify.com/s/files/1/0869/3327/4960/files/WhatsApp_Image_2024-09-13_at_11.32.29_PM_2_4d44a034-3912-4297-ac16-05342290afe1-129837.png?v=1736116654'],
    specs: {
      storage: '64GB',
      color: 'Midnight Aluminum',
      display: 'Always-On Retina display',
    },
    features: ['New Health Sensor', 'Crash Detection', 'Temperature Sensing', 'Enhanced Durability'],
    stock: 80,
  },
  {
    id: 'samsung-z-flip-6-new',
    name: 'Samsung Z Flip 6 New',
    description: 'Flex your style with the new Samsung Galaxy Z Flip 6. A stunning foldable design with an improved cover screen and powerful performance.',
    price: 1099,
    images: ['https://cdn.shopify.com/s/files/1/0869/3327/4960/files/NewProject_9.webp?v=1739206482'],
    specs: {
      storage: '256GB',
      color: 'Bora Purple',
      display: '6.7-inch Foldable Dynamic AMOLED',
    },
    features: ['Flex Mode', 'Compact Foldable Design', 'Nightography Camera', 'Enhanced Cover Screen'],
    stock: 45,
  },
  {
    id: '16-pro-max-tdra-dubai-version',
    name: '16 Pro Max Tdra Dubai Version',
    description: 'The exclusive Dubai version of the iPhone 16 Pro Max, featuring the A18 Bionic chip and a groundbreaking new camera system.',
    price: 1299,
    images: ['https://cdn.shopify.com/s/files/1/0869/3327/4960/files/16PROMAX_85347601-4b58-4e23-83a1-dddf568487bf.jpg?v=1736116681'],
    specs: {
      storage: '256GB',
      color: 'Desert Titanium',
      display: '6.9-inch Super Retina XDR',
    },
    features: ['A18 Bionic Chip', 'Tetraprism Telephoto lens', 'Action button', 'TDRA Certified'],
    stock: 30,
  },
  {
    id: 'iphone-17',
    name: 'iPhone 17',
    description: 'Get a glimpse into the future with the iPhone 17. Unveiling a radical new design and features powered by the A19 chip.',
    price: 1399,
    images: ['https://cdn.shopify.com/s/files/1/0869/3327/4960/files/WhatsApp_Image_2024-09-13_at_11.28.24_PM.jpg?v=1736116712'],
    specs: {
      storage: '256GB',
      color: 'Cosmic Blue',
      display: '6.3-inch Super Retina XDR',
    },
    features: ['A19 Chip', 'Under-display Camera', 'Haptic Buttons', 'Periscope Lens'],
    stock: 0,
  },
  {
    id: 'iphone-xs-max',
    name: 'iPhone XS Max',
    description: 'Super Retina in two sizes — including the largest display ever on an iPhone. Even faster Face ID. The smartest, most powerful chip in a smartphone.',
    price: 549,
    images: ['https://cdn.shopify.com/s/files/1/0869/3327/4960/files/xsmax.jpg?v=1736116724'],
    specs: {
      storage: '256GB',
      color: 'Gold',
      display: '6.5-inch Super Retina HD display',
    },
    features: ['A12 Bionic chip', 'Dual 12MP cameras', 'Face ID', 'Splash, Water, and Dust Resistant'],
    stock: 65,
  },
  {
    id: 'iphone-x',
    name: 'iPhone X',
    description: 'It’s all screen. An all-new 5.8-inch Super Retina screen with OLED and the powerful A11 Bionic chip.',
    price: 499,
    images: ['https://cdn.shopify.com/s/files/1/0869/3327/4960/files/x.jpg?v=1736116729'],
    specs: {
      storage: '64GB',
      color: 'Space Gray',
      display: '5.8-inch Super Retina HD display',
    },
    features: ['A11 Bionic chip', 'Face ID', 'TrueDepth Camera', 'Wireless Charging'],
    stock: 88,
  },
  {
    id: 'data-cable',
    name: 'Data Cable',
    description: 'High-speed USB-C to Lightning data and charging cable. Durable braided design for long-lasting use.',
    price: 25,
    images: ['https://cdn.shopify.com/s/files/1/0869/3327/4960/files/charging_cable.webp?v=1740743755'],
    specs: {
      storage: 'N/A',
      color: 'White',
      display: 'N/A',
    },
    features: ['USB-C to Lightning', 'Fast Charging', 'Braided Cable', '1 Meter Length'],
    stock: 200,
  }
];
