import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'iphone-15-pro',
    name: 'iPhone 15 Pro',
    description:
      'The ultimate iPhone. A17 Pro chip. A customizable Action button. The most powerful iPhone camera system. And USB-C with USB 3 for superfast transfer speeds.',
    price: 999,
    images: ['https://placehold.co/600x600'],
    specs: {
      storage: '128GB',
      color: 'Natural Titanium',
      display: '6.1-inch Super Retina XDR display',
    },
    features: ['Dynamic Island', 'A17 Pro Chip', 'Pro Camera System', 'USB-C Connector'],
    stock: 50,
  },
  {
    id: 'iphone-15',
    name: 'iPhone 15',
    description: 'iPhone 15 brings you Dynamic Island, a 48MP Main camera, and USB-C — all in a durable color-infused glass and aluminum design.',
    price: 799,
    images: ['https://placehold.co/600x600'],
    specs: {
      storage: '128GB',
      color: 'Blue',
      display: '6.1-inch Super Retina XDR display',
    },
    features: ['Dynamic Island', 'A16 Bionic Chip', 'Advanced dual-camera system', 'USB-C Connector'],
    stock: 75,
  },
  {
    id: 'iphone-14',
    name: 'iPhone 14',
    description: 'A huge leap in battery life. A new, more advanced dual-camera system. A15 Bionic, the fastest chip in a smartphone.',
    price: 699,
    images: ['https://placehold.co/600x600'],
    specs: {
      storage: '128GB',
      color: 'Midnight',
      display: '6.1-inch Super Retina XDR display',
    },
    features: ['A15 Bionic Chip', 'Dual-camera system', 'Emergency SOS via satellite', 'Ceramic Shield'],
    stock: 100,
  },
  {
    id: 'iphone-se',
    name: 'iPhone SE',
    description: 'Serious power. Serious value. A15 Bionic chip and 5G. A superstar camera. All in a pocket-friendly 4.7-inch design.',
    price: 429,
    images: ['https://placehold.co/600x600'],
    specs: {
      storage: '64GB',
      color: 'Starlight',
      display: '4.7-inch Retina HD display',
    },
    features: ['A15 Bionic Chip', '5G capable', 'Advanced single-camera system', 'Home Button with Touch ID'],
    stock: 150,
  },
   {
    id: 'macbook-air-m2',
    name: 'MacBook Air M2',
    description: 'Strikingly thin design, M2 chip, and up to 18 hours of battery life.',
    price: 1099,
    images: ['https://placehold.co/600x600'],
    specs: {
      storage: '256GB SSD',
      color: 'Midnight',
      display: '13.6-inch Liquid Retina display',
    },
    features: ['M2 Chip', '1080p FaceTime HD camera', 'MagSafe 3 charging', 'Fanless design'],
    stock: 40,
  },
  {
    id: 'macbook-pro-14',
    name: 'MacBook Pro 14"',
    description: 'Supercharged by M3, M3 Pro, or M3 Max, the MacBook Pro is a beast.',
    price: 1599,
    images: ['https://placehold.co/600x600'],
    specs: {
      storage: '512GB SSD',
      color: 'Space Black',
      display: '14.2-inch Liquid Retina XDR display',
    },
    features: ['M3 Family Chips', 'ProMotion technology', 'Studio-quality mics', 'Advanced thermal system'],
    stock: 30,
  },
  {
    id: 'ipad-pro',
    name: 'iPad Pro',
    description: 'The ultimate iPad experience, with the most advanced technology in a thin and light design.',
    price: 799,
    images: ['https://placehold.co/600x600'],
    specs: {
      storage: '128GB',
      color: 'Space Gray',
      display: '11-inch Liquid Retina display',
    },
    features: ['M2 Chip', 'Pro cameras', 'Face ID', 'USB-C with Thunderbolt'],
    stock: 60,
  },
  {
    id: 'apple-watch-s9',
    name: 'Apple Watch Series 9',
    description: 'Smarter, brighter, and mightier. The S9 SiP enables a super-bright display and a magical new way to interact.',
    price: 399,
    images: ['https://placehold.co/600x600'],
    specs: {
      storage: '64GB',
      color: 'Midnight Aluminum',
      display: 'Always-On Retina display',
    },
    features: ['S9 SiP', 'Double tap gesture', 'Temperature sensing', 'Crash Detection'],
    stock: 120,
  },
  {
    id: 'airpods-pro-2',
    name: 'AirPods Pro (2nd gen)',
    description: 'Richer audio quality, up to 2x more Active Noise Cancellation, and Adaptive Transparency.',
    price: 249,
    images: ['https://placehold.co/600x600'],
    specs: {
      storage: 'N/A',
      color: 'White',
      display: 'N/A',
    },
    features: ['H2 Chip', 'Personalized Spatial Audio', 'Up to 6 hours of listening time', 'MagSafe Charging Case (USB-C)'],
    stock: 180,
  },
  {
    id: 'apple-watch-ultra-2',
    name: 'Apple Watch Ultra 2',
    description: 'Next-level adventure. The most rugged and capable Apple Watch pushes boundaries again.',
    price: 799,
    images: ['https://placehold.co/600x600'],
    specs: {
      storage: '64GB',
      color: 'Titanium',
      display: 'Always-On Retina display',
    },
    features: ['S9 SiP', 'Precision Finding for iPhone', 'Water resistant 100m', 'Customizable Action button'],
    stock: 25,
  },
  {
    id: 'imac-24',
    name: 'iMac 24"',
    description: 'You’ve never seen a computer like this before. With a strikingly thin design made possible by the Apple M3 chip.',
    price: 1299,
    images: ['https://placehold.co/600x600'],
    specs: {
      storage: '256GB SSD',
      color: 'Blue',
      display: '24-inch 4.5K Retina display',
    },
    features: ['M3 Chip', '1080p FaceTime HD camera', 'Six-speaker sound system', 'Color-matched accessories'],
    stock: 35,
  },
  {
    id: 'mac-mini',
    name: 'Mac mini',
    description: 'More muscle. More hustle. Now with the M2 or M2 Pro chip, Mac mini is a workhorse that gets the job done.',
    price: 599,
    images: ['https://placehold.co/600x600'],
    specs: {
      storage: '256GB SSD',
      color: 'Silver',
      display: 'N/A',
    },
    features: ['M2 or M2 Pro Chip', 'Compact design', 'Extensive ports', 'Unified memory'],
    stock: 55,
  },
   {
    id: 'ipad-air',
    name: 'iPad Air',
    description: 'Serious performance in a thin and light design. With the M1 chip, iPad Air is a creative and gaming powerhouse.',
    price: 599,
    images: ['https://placehold.co/600x600'],
    specs: {
      storage: '64GB',
      color: 'Blue',
      display: '10.9-inch Liquid Retina display',
    },
    features: ['M1 Chip', '12MP Ultra Wide front camera', 'Works with Apple Pencil (2nd gen)', 'Touch ID'],
    stock: 80,
  },
  {
    id: 'homepod-mini',
    name: 'HomePod mini',
    description: 'Jam-packed with innovation, HomePod mini delivers unexpectedly big sound for a speaker of its size.',
    price: 99,
    images: ['https://placehold.co/600x600'],
    specs: {
      storage: 'N/A',
      color: 'White',
      display: 'N/A',
    },
    features: ['360-degree audio', 'Siri assistant', 'Stereo pair capable', 'Intercom'],
    stock: 250,
  },
  {
    id: 'apple-tv-4k',
    name: 'Apple TV 4K',
    description: 'The Apple experience. Cinematic in every sense. With 4K Dolby Vision and HDR10+, and Dolby Atmos for immersive sound.',
    price: 129,
    images: ['https://placehold.co/600x600'],
    specs: {
      storage: '64GB',
      color: 'Black',
      display: 'N/A',
    },
    features: ['A15 Bionic chip', '4K High Frame Rate HDR', 'Siri Remote', 'Acts as a home hub'],
    stock: 90,
  },
];
